Offline doc generation support
JoshLabs/django-rest-swagger pull request #1
Opened 2017-05-19 10:54 UTC by arpit-goel

2017-05-19 12:55 UTC, SwechchhaSingh requested changes

2017-05-19 12:55 UTC, SwechchhaSingh commented on rest_framework_swagger/management/commands/generate_docs.py
> +        logger.info(u'Deleting previous docs')
This should only appear if docs are actually being deleted.

2017-05-19 12:55 UTC, SwechchhaSingh commented on rest_framework_swagger/management/commands/generate_docs.py
> +            print app[u'path']
Remove print statement.

2017-05-19 12:55 UTC, SwechchhaSingh commented on rest_framework_swagger/management/commands/generate_docs.py
> +            u'apiVersion': rfs.SWAGGER_SETTINGS.get(u'api_version', u''),
Indentation. Update at all relevant places.

2017-05-22 05:45 UTC, sandipagarwal approved these changes

2017-05-22 07:35 UTC, sandipagarwal approved these changes

2017-05-22 09:12 UTC, merged